# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /sustain/
title: Neha Nivedita
author: Nivedit
description: Full Stack Developer| Tech Speaker | Open Source Contributor
avatar: nivedit.png
email: hi@nivedit.in
github: jekyller/sustain # username
twitter: niknivedit
linkedin: neha-nivedita
stackoverflow: ryder   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
